// ! Tasks Actions
export const LOADING_TASKS = 'LOADING_TASKS';
export const TASKS_LOADED = 'TASKS_LOADED';
export const TASKS_LOADED_SUCCESS = 'TASKS_LOADED_SUCCESS';
export const LOADED_TASKS_FAIL = 'LOADED_TASKS_FAIL';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const UPDATE_TASKS_FAIL = 'UPDATE_TASKS_FAIL';

export const UPDATE_TASKS_STATUS = 'UPDATE_TASKS';
export const UPDATE_TASKS_STATUS_FAIL = 'UPDATE_TASKS_FAIL';


// ! User & auth  Actions
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';